serveurs:
  - survie
  - decimation
  - lobby
armorstand:
  survie:
    name: Survie
    x: -6.5
    y: 22
    z: 0.5
    yaw: -90.0
    pitch: 0.0
  decimation:
    name: Décimation
    x: 6.5
    y: 22
    z: 0.5
    yaw: 90.0
    pitch: 0.0
  lobby:
    name: Lobby
    x: 0.5
    y: 22
    z: 6.5
    yaw: 90.0
    pitch: 0.0